const cardData = [
    {title: "The Dictator", time:"1h 56m" ,genre:"Comedy", imageUrl: "/src/netflixappimgs/card.jpg", addToList: false, type: "movie" },
    {title: "Purple Hearts", time:"1h 32m" , genre:"Romance", imageUrl: "/src/netflixappimgs/card.jpg", addToList: false,type: "movie" },
    {title: "The Invitation", time:"2h 12m",genre:"Horror", imageUrl: "/src/netflixappimgs/card.jpg", addToList: true,type: "movie" },
    {title: "The Grinch", time:"2h 32m" ,genre:"Comedy", imageUrl: "/src/netflixappimgs/card.jpg", addToList: false, type: "movie"},
    {title: "Inception", time:"1h 02m" , genre:"Thriller", imageUrl: "/src/netflixappimgs/card.jpg", addToList: false, type: "movie" },
    {title: "The Marvels", time:"1h 32m",genre:"Action", imageUrl: "/src/netflixappimgs/card.jpg", addToList: true, type: "movie" },
    {title: "Joker", time:"1h 32m" ,genre:"Comedy", imageUrl: "/src/netflixappimgs/card.jpg", addToList: false,type: "movie" },
    {title: "Leo", time:"1h 32m" , genre:"Romance", imageUrl: "/src/netflixappimgs/card.jpg", addToList: false, type: "movie" },
    {title: "The Creator", time:"1h 32m",genre:"Sci-Fi", imageUrl: "/src/netflixappimgs/card.jpg", addToList: false, type: "movie" },
    {title: "No Time to Die", time:"1h 32m" ,genre:"Comedy", imageUrl: "/src/netflixappimgs/card.jpg", addToList: true,type: "movie" },
    {title: "Candy Cane Lane", time:"1h 32m" , genre:"Romance", imageUrl: "/src/netflixappimgs/card.jpg", addToList: false,type: "movie" },
    {title: "Rustin", time:"1h 32m",genre:"Fantasy", imageUrl: "/src/netflixappimgs/card.jpg", addToList: false,type: "movie" },
    {title: "Locked In", time:"1h 32m" ,genre:"Fantasy", imageUrl: "/src/netflixappimgs/card.jpg", addToList: false,type: "movie" },
    {title: "Pain Hustlers", time:"1h 32m" , genre:"Sci-Fi", imageUrl: "/src/netflixappimgs/card.jpg", addToList: false,type: "movie" },
    {title: "Batman Begins", time:"1h 32m",genre:"Action", imageUrl: "/src/netflixappimgs/card.jpg", addToList: true,type: "movie" },
    {title: "The Nun II", time:"1h 32m" ,genre:"Horror", imageUrl: "/src/netflixappimgs/card.jpg", addToList: false,type: "movie" },
    {title: "Family Switch", time:"1h 32m" , genre:"Comedy", imageUrl: "/src/netflixappimgs/card.jpg", addToList: false,type: "movie" },
    {title: "Inside Out", time:"1h 32m",genre:"Animated", imageUrl: "/src/netflixappimgs/card.jpg", addToList: true,type: "movie" },
    {title: "The Departed", time:"1h 32m" ,genre:"Drama", imageUrl: "/src/netflixappimgs/card.jpg", addToList: false,type: "movie" },
    {title: "Avatar", time:"1h 32m" , genre:"Romance", imageUrl: "/src/netflixappimgs/card.jpg", addToList: false,type: "movie" },
    {title: "The Notebook", time:"1h 32m",genre:"Romance", imageUrl: "/src/netflixappimgs/card.jpg", addToList: true,type: "movie" },
    {title: "Dear John", time:"1h 32m" ,genre:"Romance", imageUrl: "/src/netflixappimgs/card.jpg", addToList: false, type: "movie" },
    {title: "Catch Me If You Can", time:"1h 32m" , genre:"Thriller", imageUrl: "/src/netflixappimgs/card.jpg", addToList: true, type: "movie" },
    {title: "Fight Club", time:"1h 32m",genre:"Drama", imageUrl: "/src/netflixappimgs/card.jpg", addToList: false,type: "movie" },
    {title: "Thor", time:"1h 32m" ,genre:"Comedy", imageUrl: "/src/netflixappimgs/card.jpg", addToList: false, type: "movie" },
    {title: "Momento", time:"1h 32m" , genre:"Thriller", imageUrl: "/src/netflixappimgs/card.jpg", addToList: false, type: "movie" },
    {title: "Next Goal Wins", time:"1h 32m",genre:"Comedy", imageUrl: "/src/netflixappimgs/card.jpg", addToList: false, type: "movie" },
    {title: "The Godfather", time:"1h 32m" ,genre:"Drama", imageUrl: "/src/netflixappimgs/card.jpg", addToList: true, type: "movie" },
    {title: "Finding Nemo", time:"1h 32m" , genre:"Animated", imageUrl: "/src/netflixappimgs/card.jpg", addToList: false, type: "movie" },
    {title: "Toy Story", time:"1h 32m",genre:"Animated", imageUrl: "/src/netflixappimgs/card.jpg", addToList: false, type: "movie" },
    {title: "The Dictator", time:"1h 56m" ,genre:"Comedy", imageUrl: "/src/netflixappimgs/card.jpg", addToList: false, type: "tvshow" },
    {title: "Purple Hearts", time:"1h 32m" , genre:"Romance", imageUrl: "/src/netflixappimgs/card.jpg", addToList: false,type: "tvshow" },
    {title: "The Invitation", time:"2h 12m",genre:"Horror", imageUrl: "/src/netflixappimgs/card.jpg", addToList: true,type: "tvshow" },
    {title: "The Grinch", time:"2h 32m" ,genre:"Comedy", imageUrl: "/src/netflixappimgs/card.jpg", addToList: false, type: "tvshow"},
    {title: "Inception", time:"1h 02m" , genre:"Thriller", imageUrl: "/src/netflixappimgs/card.jpg", addToList: false, type: "tvshow" },
    {title: "The Marvels", time:"1h 32m",genre:"Action", imageUrl: "/src/netflixappimgs/card.jpg", addToList: true, type: "tvshow" },
    {title: "Joker", time:"1h 32m" ,genre:"Comedy", imageUrl: "/src/netflixappimgs/card.jpg", addToList: false,type: "tvshow" },
    {title: "Leo", time:"1h 32m" , genre:"Romance", imageUrl: "/src/netflixappimgs/card.jpg", addToList: false, type: "tvshow" },
    {title: "The Creator", time:"1h 32m",genre:"Sci-Fi", imageUrl: "/src/netflixappimgs/card.jpg", addToList: false, type: "tvshow" },
    {title: "No Time to Die", time:"1h 32m" ,genre:"Comedy", imageUrl: "/src/netflixappimgs/card.jpg", addToList: true,type: "tvshow" },
    {title: "Candy Cane Lane", time:"1h 32m" , genre:"Romance", imageUrl: "/src/netflixappimgs/card.jpg", addToList: false,type: "tvshow" },
    {title: "Rustin", time:"1h 32m",genre:"Fantasy", imageUrl: "/src/netflixappimgs/card.jpg", addToList: false,type: "tvshow" },
    {title: "Locked In", time:"1h 32m" ,genre:"Fantasy", imageUrl: "/src/netflixappimgs/card.jpg", addToList: false,type: "tvshow" },
    {title: "Pain Hustlers", time:"1h 32m" , genre:"Sci-Fi", imageUrl: "/src/netflixappimgs/card.jpg", addToList: false,type: "tvshow" },
    {title: "Batman Begins", time:"1h 32m",genre:"Action", imageUrl: "/src/netflixappimgs/card.jpg", addToList: true,type: "tvshow" },
    {title: "The Nun II", time:"1h 32m" ,genre:"Horror", imageUrl: "/src/netflixappimgs/card.jpg", addToList: false,type: "tvshow" },
    {title: "Family Switch", time:"1h 32m" , genre:"Comedy", imageUrl: "/src/netflixappimgs/card.jpg", addToList: false,type: "tvshow" },
    {title: "Inside Out", time:"1h 32m",genre:"Animated", imageUrl: "/src/netflixappimgs/card.jpg", addToList: true,type: "tvshow" },
    {title: "The Departed", time:"1h 32m" ,genre:"Drama", imageUrl: "/src/netflixappimgs/card.jpg", addToList: false,type: "tvshow" },
    {title: "Avatar", time:"1h 32m" , genre:"Romance", imageUrl: "/src/netflixappimgs/card.jpg", addToList: false,type: "tvshow" },
    {title: "The Notebook", time:"1h 32m",genre:"Romance", imageUrl: "/src/netflixappimgs/card.jpg", addToList: true,type: "tvshow" },
    {title: "Dear John", time:"1h 32m" ,genre:"Romance", imageUrl: "/src/netflixappimgs/card.jpg", addToList: false, type: "tvshow" },
    {title: "Catch Me If You Can", time:"1h 32m" , genre:"Thriller", imageUrl: "/src/netflixappimgs/card.jpg", addToList: true, type: "tvshow" },
    {title: "Fight Club", time:"1h 32m",genre:"Drama", imageUrl: "/src/netflixappimgs/card.jpg", addToList: false,type: "tvshow" },
    {title: "Thor", time:"1h 32m" ,genre:"Comedy", imageUrl: "/src/netflixappimgs/card.jpg", addToList: false, type: "tvshow" },
    {title: "Momento", time:"1h 32m" , genre:"Thriller", imageUrl: "/src/netflixappimgs/card.jpg", addToList: false, type: "tvshow" },
    {title: "Next Goal Wins", time:"1h 32m",genre:"Comedy", imageUrl: "/src/netflixappimgs/card.jpg", addToList: false, type: "tvshow" },
    {title: "The Godfather", time:"1h 32m" ,genre:"Drama", imageUrl: "/src/netflixappimgs/card.jpg", addToList: true, type: "tvshow" },
    {title: "Finding Nemo", time:"1h 32m" , genre:"Animated", imageUrl: "/src/netflixappimgs/card.jpg", addToList: false, type: "tvshow" },
    {title: "Toy Story", time:"1h 32m",genre:"Animated", imageUrl: "/src/netflixappimgs/card.jpg", addToList: false, type: "tvshow" },
];

export default cardData;